// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecrementSignals():Promise<Array<number>>;

export function GetCount():Promise<string>;

export function GetHTML():Promise<string>;

export function IncHTML():Promise<Array<number>>;

export function Increment():Promise<number>;

export function IncrementSignals():Promise<Array<number>>;

export function RemoveDivHTML():Promise<Array<number>>;

export function RemoveSignalsUI():Promise<Array<number>>;
