// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCount():Promise<string>;

export function GetHTML():Promise<string>;

export function Inc():Promise<string>;

export function IncHTML():Promise<string>;
