// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecrementFragments():Promise<Array<number>>;

export function DecrementSignals():Promise<Array<number>>;

export function ExecuteScript():Promise<Array<number>>;

export function GetCount():Promise<string>;

export function GetHTML():Promise<string>;

export function Increment():Promise<number>;

export function IncrementFragments():Promise<Array<number>>;

export function IncrementSignals():Promise<Array<number>>;

export function RemoveFragmentsUI():Promise<Array<number>>;

export function RemoveSignalsUI():Promise<Array<number>>;
