// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCount() {
  return window['go']['main']['App']['GetCount']();
}

export function GetHTML() {
  return window['go']['main']['App']['GetHTML']();
}

export function Inc() {
  return window['go']['main']['App']['Inc']();
}
