// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecrementFragments() {
  return window['go']['main']['App']['DecrementFragments']();
}

export function DecrementSignals() {
  return window['go']['main']['App']['DecrementSignals']();
}

export function ExecuteScript() {
  return window['go']['main']['App']['ExecuteScript']();
}

export function GetCount() {
  return window['go']['main']['App']['GetCount']();
}

export function GetHTML() {
  return window['go']['main']['App']['GetHTML']();
}

export function Increment() {
  return window['go']['main']['App']['Increment']();
}

export function IncrementFragments() {
  return window['go']['main']['App']['IncrementFragments']();
}

export function IncrementSignals() {
  return window['go']['main']['App']['IncrementSignals']();
}

export function RemoveFragmentsUI() {
  return window['go']['main']['App']['RemoveFragmentsUI']();
}

export function RemoveSignalsUI() {
  return window['go']['main']['App']['RemoveSignalsUI']();
}
