// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecrementSignals() {
  return window['go']['main']['App']['DecrementSignals']();
}

export function GetCount() {
  return window['go']['main']['App']['GetCount']();
}

export function GetHTML() {
  return window['go']['main']['App']['GetHTML']();
}

export function IncHTML() {
  return window['go']['main']['App']['IncHTML']();
}

export function Increment() {
  return window['go']['main']['App']['Increment']();
}

export function IncrementSignals() {
  return window['go']['main']['App']['IncrementSignals']();
}

export function RemoveDivHTML() {
  return window['go']['main']['App']['RemoveDivHTML']();
}

export function RemoveSignalsUI() {
  return window['go']['main']['App']['RemoveSignalsUI']();
}
